[pytest]
testpaths = 
    consumers/aws/sqs-gmail-consumer/tests
    consumers/aws/sqs-slack-consumer/tests
    webhooks/aws/generic-webhook/tests
    webhooks/aws/gmail-webhook/tests
    webhooks/aws/slack-webhook/tests
    webhooks/aws/voice-webhook/tests
python_files = test_*.py
python_functions = test_*
addopts = -v
asyncio_mode = auto
